### ISSUE TITLE
DOMException, request is already pending

### ISSUE THREAD

**Issue by ndlaroy99** [mkalioby/django-passkeys#16]
I'm experiencing this issue with my project. I deployed mirroring the example project very closely:

Uncaught (in promise) login:1 DOMExcention: request is already pending.
![Screenshot 2023-07-21 at 11 44 43 PM](https://github.com/mkalioby/django-passkeys/assets/8979122/ea038e27-371a-441c-83bf-e542a27ba92a)

These issues appear to be a misconfig in the provided JS for passkeys? I am deploying using GCP Cloud Run and have run 'collectstatic' --> 'makemigrations' --> 'migrate'. I have tested and received the same error in 3 different browsers on macOS (Safari, Brave, and Arc; all fully up-to-date. Mac is running macOS Ventura 13.4c1).

**Comment by mkalioby** [comment]
I think you didn't include `passkey.js` in the second page,  can you share the repo?

**Comment by mkalioby** [comment]
Can you please separate these in two issues to make communication easier?

**Comment by mkalioby** [comment]
Do you use conditionalUI?

**Comment by ndlaroy99** [comment]
Yes, I did!

**Comment by mkalioby** [comment]
This one is a bug, the function shall abort the conditionalUI first, I'll try to push fix this evening and let you know.

**Comment by mkalioby** [comment]
I fixed the bug in a prelease, please install it by

```sh
pip install django-passkeys==1.2.5b1
```
Please let me know if the issue is fixed to release it.

**Comment by ndlaroy99** [comment]
This is the error now:

![image](https://github.com/mkalioby/django-passkeys/assets/8979122/95493965-3a64-4fbd-abd7-32cfa9479079)

**Comment by ndlaroy99** [comment]
This bug is fixed now! Not sure if these console errors are of concern, but these popped up as well

![image](https://github.com/mkalioby/django-passkeys/assets/8979122/0d80dbd7-f613-4856-ad42-653ce81ebe13)

**Comment by mkalioby** [comment]
No the abort with no reason is OK
