### ISSUE TITLE
Start is not defined error

### ISSUE THREAD

**Issue by ndlaroy99** [mkalioby/django-passkeys#17]
#2: Uncaught ReferenceError: (index): 114 cart ic not defined OTHER X):114:71)
![Screenshot 2023-07-21 at 11 47 10 PM](https://github.com/mkalioby/django-passkeys/assets/8979122/ee8e961f-2e16-4059-a4b4-0dd01dd5ba0c)

**Comment by mkalioby** [comment]
`start()` exists in [Line 70 in PassKeys.html()](https://github.com/mkalioby/django-passkeys/blob/5df5514734e1fbcf04ca7bf6fc31af8612b2050f/passkeys/templates/PassKeys.html#L70), how did you create that page?

**Comment by ndlaroy99** [comment]
Here is a link to my repo

**Comment by mkalioby** [comment]
Thanks for sharing the code. It makes debugging the issue much easier.

You forgot to add block called 'head' in your `base.html` 
```
 {% block head %}
 {% endblock %}
```

**Comment by ndlaroy99** [comment]
This is the error now

![image](https://github.com/mkalioby/django-passkeys/assets/8979122/6caa3a52-0b2c-4163-baa0-731cb6b87ef0)

**Comment by mkalioby** [comment]
Add Jquery to your code

**Comment by ndlaroy99** [comment]
Please review my repo again if you wouldn't mind. I am calling jQuery my base.html and extending base.html for each template.

**Comment by mkalioby** [comment]
There is two instances of jQuery, remove one and try again

**Comment by mkalioby** [comment]
Try to move block head after calling your scripts. I think that is the issue.

**Comment by mkalioby** [comment]
Sure, you can copy the code from [Passkeys.html](https://github.com/mkalioby/django-passkeys/blob/main/passkeys/templates/PassKeys.html) and put in your app in an app before passkeys so you can customize it as you like.
