### ISSUE TITLE
mobile client app integration sample doc and application 

### ISSUE THREAD

**Issue by development-lnxct** [mkalioby/django-passkeys#19]
hello passkeys team.
as per your given django example is good.
but when we are trying to integrate it will flutter based so we not getting complete idea how to use this with mobile app.
so better if you provide some api things and mobile flutter based sample application by using django rest api.

**Comment by mkalioby** [comment]
Dear @development-lnxct ,

Currently, we don't have the capacity to do this but we can work together to do this, as Passkeys in Mobile Application is very challenging and require a lot of configurations.

In the meantime, I recommend that you check [JustPass.me](https://justpass.me) as they provide an easy way to integrate passkeys for mobile and web for several frameworks including Flutter and Django.

**Comment by development-lnxct** [comment]
Yes I have checked that
But we are not interested to involve 3rd party service.
Because just pass.me is 3rd party service provider.
And we want to keep all data on our server  .

Yes if you can guide us then definitely we can write mobile app. But we
have not details knowledge about pass keys related.

So yes we are ready to work with you together.

Thanks
Dipen

**Comment by zaghoo-amwal** [comment]
Dipen,
Founder of Justpass here. 
Building your own passkeys solutions for mobile apps is a daunting task with at least 2-3 months of dev work/testing. You can definitely do it yourself,  but you're essentially valuing your own time at less than $29/month. 
Our goal is to help indie devs launch businesses and apps fast. But I understand if time is not a concern to you!

**Comment by development-lnxct** [comment]
@zaghoo-amwal  things is we have not any issue pay $29/month.

we don't want to dependent on 3rd party service and we want to keep our all data on our own server.
otherwise we have not any issue to use your service and yes i know of course it cheaper your solution then our development cost.

Thanks

**Comment by mkalioby** [comment]
Hello @development-lnxct,
Passkeys is the integration of 2 main protocols, Web Authentication API and CTAP.
1. **Web Authentication** handles the communication between your app and browser to deal with the credentials either by create  or get
2. **CTAP** is the Client-To-Authenticator-Protocol which specifies the communication between Browser and different authenticator to make sure that the browser can create or ask the authenticator to sign a challenge.

Currently, django-passkeys handles Web Authentication only as it support web applications. Going to mobile application you need to implement Client part of CTAP (as the appl will be the client) and this is different in iOS from Andorid.

According to my knowledge, there is no libraries that interface Passkeys on all platforms to multiplatform (i.e. no flutter library that implement CTAP on all OSes) yet.

[Apple Docs](https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_passkeys/)
[Andorid Credentials Manager](https://developer.android.com/jetpack/androidx/releases/credentials)

Best of luck

**Comment by zaghoo-amwal** [comment]
@development-lnxct  Wondering if you have some progress on native passkey implementation? We have extended our solution to enable bespoke integration with major identity providers (Firebase, Auth0 and even social logins). 

Happy to discuss some white-label options as well
