### ISSUE TITLE
reg_begin ValueError

### ISSUE THREAD

**Issue by jacopsd** [mkalioby/django-passkeys#2]
When starting a registration, and reg_begin() is called, facing following issue:
   "ValueError: Error parsing field user for PublicKeyCredentialCreationOptions"

When replacing line #61 in FIDO2.py
`        u'id': request.user.username.encode("utf8"),`

with:
`        u'id': "testuserid",`

it works, so this seems to be related to string encoding.

**Comment by mkalioby** [comment]
Hello, 

The `id` shall be `bytes` not  `str`.
What is the value of the username for the current user.

**Comment by mkalioby** [comment]
Shall be fixed in 1.1.1.
