### ISSUE TITLE
github releases are incomplete/outdated

### ISSUE THREAD

**Issue by ThomasWaldmann** [mkalioby/django-passkeys#20]
on pypi, there is 1.2.5, on github releases page, there is 1.0.0 - that might confuse some people.

suggestion:
- at least create a git tag for each release you do
- better: create a github release for each release. in case you choose to sign your releases with gpg, you can also upload your gpg signature to the github release, together with the sdist you also upload to pypi (pypi discourages uploading gpg sigs since a while, also good to have a backup of the sdist)
- alternatively: remove all github releases and only rely on pypi (having tags in git would be a good idea nonetheless)

**Comment by mkalioby** [comment]
Cleared releases.

Thanks

**Comment by ThomasWaldmann** [comment]
https://github.com/mkalioby/django-passkeys/tags

A good idea would be to set the missing tags to create a relation between the pypi releases and what's in git.
