### ISSUE TITLE
Created Passkeys don't persist for login and username is not identified correctly.

### ISSUE THREAD

**Issue by ndlaroy99** [mkalioby/django-passkeys#22]
For reference, I am deploying my Django application using GCP Cloud Run based on an image I have hosted in the GCP Artifact Registry.

Every time I create a passkey (platform-agnostic, I've tried both on iOS and Windows), it only persists for a short while before the app appears to 'throw' the passkey away. If I were to click 'login with passkeys,' the credential combo is rejected. I can authenticate successfully with my username and password instead of the passkey and when I navigate to the 'My Passkeys' page after logging back in, it says 'You didn't have any keys yet.'

I believe there may be an issue with persisting the passkey within my application. The device that is creating the passkey has the right credential but the application is 'forgetting it' which is leading to failure to authenticate.

Thoughts?

**Comment by mkalioby** [comment]
How are you reaching your container and where is your database.. Please note that the key info is stored in db per user and if you recycle the db, all keys are rejected. Also you need a fixrd domain as changing domains will fail the request on authenticator.

**Comment by mkalioby** [comment]
Can you share your FIDO_Server settings and login page url.

**Comment by ndlaroy99** [comment]
Sure thing. See below. The URL of the website is nbc.northbrook-church.com.

![image](https://github.com/mkalioby/django-passkeys/assets/8979122/9e7013b4-40e9-47b1-965c-e35fa21e531d)

**Comment by mkalioby** [comment]
Can you please sure a screenshot of your browser with login page.

**Comment by ndlaroy99** [comment]
![Screenshot 2023-08-02 at 9 26 43 AM](https://github.com/mkalioby/django-passkeys/assets/8979122/c8a9f58b-3c3b-4f3e-89d6-58fe2bef2127)

**Comment by mkalioby** [comment]
Connect to the database and check `passkeys_userpasskey` table content

**Comment by ndlaroy99** [comment]
I cannot connect to the database as it is inside of the container that I am running which is only accessible on Port 8080. Perhaps I need to split out the database to its own container first.

**Comment by ndlaroy99** [comment]
Great point. I’ll do that

**Comment by mkalioby** [comment]
Any update?

**Comment by ndlaroy99** [comment]
I'm working on packaging the database into another container so that I can access it separately from the main app container. Sorry I haven't had much time to work on this the past week.
