### ISSUE TITLE
regression in commit de002a3 when using a username filed not called "username"

### ISSUE THREAD

**Issue by eric-intuitem** [mkalioby/django-passkeys#25]
Django allows to set a username field that is not called "username", thanks to the  USERNAME_FIELD variable. It is very common to set it to 'email'.
Before commit de002a3, this was supported by django-passkeys, but not after.
This comes from a change at line 25 passkeys/FIDO2.py
 - return [AttestedCredentialData(websafe_decode(uk.token)) for uk in UserPasskey.objects.filter(user = user)]
 + return [AttestedCredentialData(websafe_decode(uk.token)) for uk in UserPasskey.objects.filter(user__username = user)]
When reverting this change in the last version, the issue is fixed and no drawback has been observed.

**Comment by mkalioby** [comment]
Got it.  Will work on it tomorrow and let you know

**Comment by eric-intuitem** [comment]
Hi Mohamed,
It works well on my side.
Thanks,
Eric

From: Mohamed El-Kalioby ***@***.***>
Date: Tuesday, 31 October 2023 at 16:25
To: mkalioby/django-passkeys ***@***.***>
Cc: Eric Laubacher ***@***.***>, Author ***@***.***>
Subject: Re: [mkalioby/django-passkeys] regression in commit de002a3 when using a username filed not called "username" (Issue #25)

please try v1.2.6b1 available here
https://pypi.org/project/django-passkeys/1.2.7b1/
and let me know
