### ISSUE TITLE
Registration Failed Error

### ISSUE THREAD

**Issue by smark-1** [mkalioby/django-passkeys#26]
Every time I try to add a new token after adding the token, I get an error "Registration Failed as Error on server, please try again later".

On the server it looks like:
```
  File "C:\Users\...program\venv\lib\site-packages\fido2\server.py", line 269, in register_complete
    raise ValueError("Invalid origin in CollectedClientData.")
ValueError: Invalid origin in CollectedClientData.

```

**Comment by mkalioby** [comment]
What is the value of FIDO_SERVER_ID and your how do you access the webapp?

**Comment by smark-1** [comment]
FIDO_SERVER_ID = "localhost"
running in the chrome and firefox browsers
python 3.10 on windows

**Comment by mkalioby** [comment]
What is the url in your browser. You cant use 127.0.0.1. It shall be localhost

**Comment by smark-1** [comment]
the url is localhost

**Comment by mkalioby** [comment]
Please send the body for the ```
reg/complete
``` endpoint

**Comment by smark-1** [comment]
I got it to work using django-extensions.
python manage.py runserver_plus --cert-file cert.crt

**Comment by mkalioby** [comment]
Or use django-sslserver
