### ISSUE TITLE
Registration Failed as NotAllowedError

### ISSUE THREAD

**Issue by riclan** [mkalioby/django-passkeys#30]
I did implement passkeys with django-passkeys library (great work, thanks!!!)... and it did sort of work (never quite finished the project)... but when I returned recently it was failing completely... as in whenever I try to register/enrol a new authentication method (external phone --> fingerprint...) it gives me:

"Registration Failed as NotAllowedError: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client., try again"

it does find the phone it reads the fingerprint and progresses through some stages of the enrolment... but fails to add the method.

After a few attempt to debug... I also discovered that even the demo on webauthn.io fails... 
So has the standard evolved? Am I getting this totally wrong?

![webauthn io](https://github.com/mkalioby/django-passkeys/assets/89016299/1f0b2936-895f-4549-90df-12ac08b78077)

Ahh so yes I went back to your example from django-passkeys (screenshot below)... and set it up on localhost... with keyattachment = None and trying to authenticate with fingerprint reader on external android phone also got the same trouble.... 

![django-passkey](https://github.com/mkalioby/django-passkeys/assets/89016299/deb69633-c242-49f8-a0cf-0995d88ae10d)

**Comment by riclan** [comment]
Ahh so yes I went back to your example from django-passkeys (second screenshot)... and set it up on localhost... with keyattachment = None and also got the same trouble....

**Comment by mkalioby** [comment]
Are you trying Chrome more than 109 on localhost with self-signed certificate? if yes, you need to either host on a proper domain with a proper SSL certificate or Test on old chrome or chromium browser.

**Comment by riclan** [comment]
Ok... I'm on a variant based on Chromium 120.0.6099.144... cheers

**Comment by mkalioby** [comment]
Any update?

**Comment by mkalioby** [comment]
Try chrome/chromium 109 or below. Starting chrome 110 Google stopped passkeys on servers without a proper ssl certificates. To answer your question, no the code is different as django-mfa2 doesn't support resident keys (which separates passkeys from webauthn) as it is used as a second factor not as a single factor

**Comment by mkalioby** [comment]
You can always try latest firefox

**Comment by 41WhiteElephants** [comment]
I'll check firefox, thx

**Comment by 41WhiteElephants** [comment]
Tried Firefox 121.0,  I get error below :/

![image](https://github.com/mkalioby/django-passkeys/assets/18052257/11c00fe6-0c5b-4854-8a1e-582f94e312f0)

**Comment by mkalioby** [comment]
What is your OS?

**Comment by 41WhiteElephants** [comment]
Ubuntu 20.04

**Comment by riclan** [comment]
So I have tried an old version of chromium ( Version 103.0.5046.0 (Developer Build) (64-bit))... but it fails as well --- in a slightly different manner... 

![passkeys_chromium](https://github.com/mkalioby/django-passkeys/assets/89016299/d297724a-750a-45f8-b7ba-b538b01f39ba)

I suspect this is most likely a problem with not having an old browsers on the phone as well.... 
... it would be nice to get a setup that allows local testing including the authentication.

**Comment by riclan** [comment]
so cancelling that dialogue the android phone becomes an option but subsequently i get the sort of same error... 

![chromium_same_fail](https://github.com/mkalioby/django-passkeys/assets/89016299/2adddfb0-88cf-41e3-881a-b39edb0d2298)

The console gives some more info:
"
DevTools failed to load source map: Could not load content for https://localhost:8002/static/passkeys/js/bootstrap-toggle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
(index):230 
{publicKey: {…}}
publicKey:
authenticatorSelection: {residentKey: 'preferred', requireResidentKey: false}
challenge: 
ArrayBuffer(32)
excludeCredentials: []
pubKeyCredParams: (6) [{…}, {…}, {…}, {…}, {…}, {…}]
rp: {name: 'TestApp', id: 'localhost'}
user: {name: 'lala', id: ArrayBuffer(4), displayName: Array(0)}
[[Prototype]]: Object
[[Prototype]]: Object
(index):232 publicKey.authenticatorSelection.userVerification was not set to any value in Web Authentication navigator.credentials.create() call. This defaults to 'preferred', which is probably not what you want. If in doubt, set to 'discouraged'. See https://chromium.googlesource.com/chromium/src/+/master/content/browser/webauth/uv_preferred.md for details
(anonymous)	@	(index):232
Promise.then (async)		
begin_reg	@	(index):227
onclick	@	(index):1
"

**Comment by mkalioby** [comment]
I'll test tomorrow on Ubuntu and let you know.

**Comment by mkalioby** [comment]
Hello guys,

Just check the `KEY_ATTACHMENT` to `None` in the  `example/test_app/settings.py`. This issue is affecting only Linux as Platform authenticators aren't supported

**Comment by riclan** [comment]
Hey thanks so much for looking into this... but in my case the key_attachment has been set to None all along... that does not fix the problem for me. 

... or are you saying linux does not support this at all? (I'm on linux)

**Comment by mkalioby** [comment]
Linux supports mainly the cross-platform devices aka security keys.

Here Firefox 121 on Ubuntu 22.04
![Selection_668](https://github.com/mkalioby/django-passkeys/assets/10414020/7c52e80e-8cf2-40c9-9a63-d36c4ab481a7)

**Comment by riclan** [comment]
ok so I have tried those webpage examples (webauthn.io, passkeys.io) on a windows machine (chromium 120 and edge)... and they all fail.
So I have a feeling there is something pretty wrong with that browser implementation...

**Comment by mkalioby** [comment]
I tried both on Ubuntu and both worked as expected what is the type of the security key, you are using. May be it doesn't support FIDO2

**Comment by riclan** [comment]
Well it did work before... with your example as well as on those webpages... 
I would like to use the fingerprint from my android (13) phone. 

Updated firefox on linux... but alas no joy...

Thanks for all you help... it might just have to wait.

**Comment by mkalioby** [comment]
That  won't work on Firefox, you need a chromium based browser for that.

**Comment by riclan** [comment]
yeah i thought so and to be fair: it never got very far on firefox...

My apologies... I just tried it with an old phone on android 9 ---- and it works... 
so if all  things it is this newer phone... I have to find out more...

**Comment by riclan** [comment]
Thanks Mohamed...I thinks it's closed..  it's either the hardware or the Android version or both together...So nothing to do with Django-Passkeys.Thanks for looking into it.Erik--Sent from my Android phone with 1&1 Mail. Please excuse my brevity.On 2/13/24, 12:13 Mohamed El-Kalioby ***@***.***> wrote:

   
  I'll close this issue and you reopen another one if you need more help
