### ISSUE TITLE
Unable to use Mac as passkey device / registration not working

### ISSUE THREAD

**Issue by kakulukia** [mkalioby/django-passkeys#7]
Hi,

i somehow got this module working, am seeing the add passkey option and can initiate the process via Chrome, but my mac is missing from possible devices. 

This is how it looks like at https://webauthn.me/:
![SCR-20230610-gon](https://github.com/mkalioby/django-passkeys/assets/96352/981494d2-1ff6-45dc-b64b-d68b692ba10b)
It prompts my username and chooses the Mac as the default device. After clicking "user different device" i get those options
![SCR-20230610-gkr](https://github.com/mkalioby/django-passkeys/assets/96352/58937900-e986-47df-a73b-6a84f8eff64e)

With django passkeys it looks like this
![SCR-20230610-gq5](https://github.com/mkalioby/django-passkeys/assets/96352/9c58e4ea-f978-40bb-86e4-8013fb19f79a)

I have some other trouble with the associated pixel device. Its not working at all. Not sure why. But sanning the QR-code for a new device, i just get an unknown error: "Registration Failed as Error on server, please try again later, try again"

The Django log has this: raise ValueError("Invalid origin in CollectedClientData.")

Not sure what im doing wrong. :/
Does it actually work with localhost?

No hints in the JS console.

I used the proposed defaults:
FIDO_SERVER_ID = "localhost"  # Server rp id for FIDO2, it the full domain of your project
FIDO_SERVER_NAME = "TestApp"

**Comment by mkalioby** [comment]
Chrome on Mac works fine.

The error indicates you are using a domain different than localhost,  What is the url where is your server is running in browser. 

P.S you cant use 127.0.0.1 in the browser, you shall use localhost

**Comment by kakulukia** [comment]
Im starting the process at http://localhost:8000/passkeys/

**Comment by kakulukia** [comment]
Shall i add the port?

**Comment by kakulukia** [comment]
No, addings the port aint working at all:
Registration Failed as SecurityError: The relying party ID is not a registrable domain suffix of, nor equal to the current domain., try again

**Comment by kakulukia** [comment]
I had a quick look at the example provided. Do i have to use SSL for passkeys to work? Or why does your example use django-sslserver?

**Comment by mkalioby** [comment]
Yes, https is required for passkeys to work and I just checked HTTP fails not HTTPS is working fine.

**Comment by kakulukia** [comment]
okay, this should definitely be mentioned in the onboarding steps! :D

Im getting there one step at a time.

**Comment by kakulukia** [comment]
Okay, confirmed. This works fine with SSL enabled. Will integrate that in my onboarding steps update pull request.

If its okay with you id like to also strip down any optional code or dependencies.

**Comment by mkalioby** [comment]
Sure, lets see what to remove
